project_name: schemahero
release:
  github:
    owner: schemahero
    name: schemahero
builds:
  - id: kubectl-schemahero
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    env:
      - CGO_ENABLED=0
    main: cmd/kubectl-schemahero/main.go
    ldflags: -s -w
      -X github.com/schemahero/schemahero/pkg/version.version={{.Version}}
      -X github.com/schemahero/schemahero/pkg/version.gitSHA={{.Commit}}
      -X github.com/schemahero/schemahero/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: kubectl-schemahero
    hooks: {}
  - id: manager
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: cmd/manager/main.go
    ldflags: -s -w
      -X github.com/schemahero/schemahero/pkg/version.version={{.Version}}
      -X github.com/schemahero/schemahero/pkg/version.gitSHA={{.Commit}}
      -X github.com/schemahero/schemahero/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: manager
    hooks: {}
archives:
  - id: kubectl-schemahero
    builds:
      - kubectl-schemahero
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
  - id: schemahero
    builds:
      - schemahero
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
dockers:
  - dockerfile: ./deploy/Dockerfile.manager
    image_templates:
      - "schemahero/schemahero-manager:{{.Version}}"
    binaries:
      - manager
